# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: alex.nisnevich.com
title: AlexNisnevich.blog
author: Alex Nisnevich
email: alex.nisnevich@gmail.com

# configuration for enhancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-345959-11

github:
  username: AlexNisnevich

disqus:
  id: alex-nisnevich-blog

# settings

show_related_posts: false # enable once there's actually more than a few posts
